version: '3.6'

services:
        nginx:
                build: ./nginx
                ports:
                        - 1337:80
                depends_on:
                        - web
        web:
                build: .
                command: gunicorn web_trial.robocool.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - .:/srv
                ports:
                        - 8000:8000
                env_file:
                        - .env.dev
                depends_on:
                        - db
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                environment:
                        - POSTGRES_USER=dkoval_db
                        - POSTGRES_PASSWORD=barmaley
                        - POSTGRES_DB=dkoval_db
volumes:
        postgres_data:

