version: '3.6'

services:
        nginx:
                build: ./nginx
                labels:
                        "autoheal": "true"
                ports:
                        - 1337:80
                depends_on:
                        - web
        web:
                build: .
                command: gunicorn web_trial.robocool.wsgi:application --bind 0.0.0.0:8000
                volumes:
                        - .:/srv
                expose:
                        - 8000
                env_file:
                        - .env.dev
                labels:
                        "autoheal": "true"
                depends_on:
                        - db
        db:
                image: postgres:12.0-alpine
                volumes:
                        - postgres_data:/var/lib/postgresql/data/
                env_file:
                        - .env.db
        autoheal:
                image: willfarrell/autoheal
                container_name: autoheal
                volumes:
                        - '/var/run/docker.sock:/var/run/docker.sok'
                environment:
                        - AUTOHEAL_INTERVAL=10
volumes:
        postgres_data:

